# Gradle
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

# Parchment
parchment_minecraft_version=1.21.4
parchment_mappings_version=2025.01.19

# Environment Properties

minecraft_version=1.21.4
minecraft_version_range=[1.21.4, 1.22)

neo_version=21.4.89-beta
neo_version_range=[21.4,)
loader_version_range=[4,)

## Mod Properties

mod_id=hexxit_gear
mod_name=Hexxit Gear R
mod_license=MIT
mod_version=1.0.1
mod_group_id=net.nova.hexxit_gear
mod_authors=ImVeryBad
mod_description=Hexxit Gear R tries to bring back the old Hexxit Gear into the newer versions of minecraft. Adding the new flower Hexbiscus, for collecting its petals and creating the new four armor sets in the mod.