license="${mod_license}"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
issueTrackerURL="https://github.com/Starexify/HexxiGearR/issues"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile= "../../resources/hexxit_gear_r_logo.png"
#credits=""
authors="${mod_authors}"
description='''${mod_description}'''

[modproperties.modmenu]
links=["hexxit_gear.modrinth=modrinth.com/mod/hexxit-gear-r", "hexxit_gear.curseforge=www.curseforge.com/minecraft/mc-mods/hexxit-gear-r"]
sources="https://github.com/Starexify/HexxiGearR"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
